### ISSUE TITLE
Does This Support On 1.9 GDPS?

### ISSUE THREAD

**Issue by Rxntiongaming** [Wayveyx/geometrix#1]
Is It?

**Comment by fancythedeveloper** [comment]
Maybe, but you would probably have to make a couple of changes for it to work well.

**Comment by Wayveyx** [comment]
Theoretically yeah, though a lot of the server side files have been modified and there's a few that aren't in cvolton's gdps repo. It wouldn't work straight away, but if you can figure out what all I've done to make it work, it should work fine.

**Comment by Rxntiongaming** [comment]
> Theoretically yeah, though a lot of the server side files have been modified and there's a few that aren't in cvolton's gdps repo. It wouldn't work straight away, but if you can figure out what all I've done to make it work, it should work fine.

**Ok Tnks :)**
